version: 1.0.0
jobs:
  build:
    type: approval
    docker:
      - image: circleci/node:10.8.0
    steps:
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install deps
          command: npm ci
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build application
          command: npm run build
      - run:
          name: copy modules
          command: cp -R ./node_modules ./dist && tar -zcvf ./deployment_${CIRCLE_BRANCH}_${CIRCLE_WORKFLOW_ID}.tar.gz ./dist
      - run:
          name: deploy
          command: scp -o StrictHostKeyChecking=no ./deployment_${CIRCLE_BRANCH}_${CIRCLE_WORKFLOW_ID}.tar.gz $DROPLET_USER@$DROPLET_DOMAIN:/www/sites/$DROPLET_DOMAIN/