version: 1.0.0
jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:10.8.0
    steps:
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install deps
          command: npm ci
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
            name: build application
            command: npm run build
      - run:
          - name: copy modules
          - command: cp ./node_modules ./dist
      - run:
          - name: deploy
          - command: scp ./dist/* $DROPLET_USER@DROPLET_DOMAIN:/www/sites/$DROPLET_DOMAIN