version: 1.0.0
jobs:
  build:
    docker:
      - image: node:8.15.1-alpine
    steps:
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install deps
          command: npm ci
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
            name: build application
            command: npm run build
      - run:
          name: deploy
          command: echo "this is where we'd ship off the code"