version: 1.0.0
jobs:
  build:
    docker:
      - image: circleci/node:10.8.0
    steps:
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install deps
          command: npm ci
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
            name: build application
            command: npm run build
      - store_artifacts:
          path: ./dist
          destination: dist
